---
- name: Ensure nexus system user exist
  ansible.builtin.user:
    name: "{{ nexus_system_user }}"
    createhome: yes
    home: "{{ nexus_system_path }}"

- name: Generate Nexus configuration files from template files
  become: true
  ansible.builtin.template:
    src: "nexusfiles/{{ item }}.j2"
    dest: "{{ nexus_system_path }}/{{ item }}"
    mode: '775'
    owner: "{{ nexus_system_user }}"
    group: "{{ nexus_system_user }}"
  loop:
    - nexus.properties
    - nexus.vmoptions
  notify: Restart containers

- name: Enusre Caddyfile exist on system
  become: true
  ansible.builtin.template:
    src: caddy/Caddyfile.j2
    dest: "{{ nexus_system_path }}/Caddyfile"
    owner: "{{ nexus_system_user }}"
    group: "{{ nexus_system_user }}"
  when: nexus_master_caddy | bool
  notify: Restart containers

- name: Generate docker compose file from template
  become: true
  ansible.builtin.template:
    src: "docker-compose.yml.j2"
    dest: "{{ nexus_system_path }}/docker-compose.yml"
    mode: '0664'
    owner: "{{ nexus_system_user }}"
    group: "{{ nexus_system_user }}"
  notify: Restart containers

- name: Start up Nexus master services
  become: true
  ansible.builtin.shell: docker-compose up -d
  args:
    chdir: "{{ nexus_system_path }}"
  changed_when: false

- name: Start up Nexus master services
  become: true
  ansible.builtin.shell: docker-compose up -d
  args:
    chdir: "{{ nexus_system_path }}"
  register: _nexus_result
  changed_when: (_nexus_result.stderr | regex_search('Recreating')) == 'Recreating'

- name: Update Nexus admin password with script
  block:
    - name: Enable script creation in nexus.properties
      ansible.builtin.lineinfile:
        path: "/home/nexus/nexus.properties"
        regexp: "^nexus.scripts.allowCreation="
        line: "nexus.scripts.allowCreation=true"
        state: present

    - name: Restart Nexus container to apply script creation change
      ansible.builtin.command:
        cmd: docker compose restart nexus
  
    - name: Pause for 30 seconds
      ansible.builtin.pause:
        seconds: 30

    - name: Wait for Nexus to start up
      ansible.builtin.uri:
        url: "http://192.168.0.20:8081/service/rest/v1/status/writable"
        status_code: 200
      register: result
      until: result.status == 200
      retries: 10
      delay: 20

    - name: Upload Nexus script to change admin password
      hax0sen.sonatype_nexus.nexus_script:
        url: "http://172.18.0.3:8081"
        user: admin
        password: admin123
        method: POST
        name: "change_admin_password"
        content: "{{ lookup('file', '/home/hax0sen/.ansible/collections/ansible_collections/hax0sen/sonatype_nexus/files/change_admin_password.groovy') }}"

    - name: Trigger script to change password
      hax0sen.sonatype_nexus.nexus_script_run:
        url: "http://172.18.0.3:8081"
        user: admin
        password: admin123
        name: "change_admin_password"
        body: "{{ {'new_password': nexus_admin_password} | to_json }}"

    - name: Revert script creation setting to false in nexus.properties
      ansible.builtin.lineinfile:
        path: "/home/nexus/nexus.properties"
        regexp: "^nexus.scripts.allowCreation="
        line: "nexus.scripts.allowCreation=false"
        state: present

    - name: Restart Nexus container to apply script creation change
      ansible.builtin.command:
        cmd: docker compose restart nexus

    - name: Wait for Nexus to start up
      ansible.builtin.uri:
        url: "http://192.168.0.20:8081/service/rest/v1/status/writable"
        status_code: 200
      register: result
      until: result.status == 200
      retries: 10
      delay: 20

  when: update_nexus_password | bool
