---

- name: Create user
  collection.sonatype_nexus.nexus_security_user:
    url: "http://172.18.0.3:8081"
    validate_certs: no
    username: admin
    password: admin123
    user_id: testuser
    user_password: testuser
    first_name: test
    last_name: test
    email_address: myadmin@localhost
    status: active
    roles: [
      "nx-admin"
    ]
    state: present

#Create a list of 
- name: Get Nexus scripts
  collection.sonatype_nexus.nexus_script_info:
    url: "http://172.18.0.3:8081"
    user: admin
    password: admin123
    method: GET
  register: script_list

- name: Debug script list
  debug:
    var: script_list


- name: Upload Nexus script to change admin password
  collection.sonatype_nexus.nexus_script:
    url: "http://172.18.0.3:8081"
    user: admin
    password: admin123
    method: POST
    name: "change_admin_password"
    content: "{{ lookup('file', '/home/hax0sen/.ansible/collections/ansible_collections/collection/sonatype_nexus/files/change_admin_password.groovy') }}"

# - name: Delete Nexus script to change admin password
#   collection.sonatype_nexus.nexus_script:
#     url: "http://172.18.0.3:8081"
#     user: admin
#     password: admin123
#     method: DELETE
#     name: "change_admin_password"

# - name: Trigger script 
#   collection.sonatype_nexus.nexus_script_run:
#     url: "http://172.18.0.3:8081"
#     user: admin
#     password: admin123
#     name: "change_admin_password"
#     body: "{{ {'new_password': nexus_admin_password} | to_json }}"


- name: Get Ldap servers connect to this Nexus
  collection.sonatype_nexus.nexus_security_ldap_info:
    url: "http://172.18.0.3:8081"
    user: admin
    password: admin123
    method: GET
  register: ldap_list

- name: Debug ldap list
  debug:
    var: ldap_list

- name: Create LDAP server "my-ldap-server"
  collection.sonatype_nexus.nexus_security_ldap:
    url: "http://172.18.0.3:8081"  # Nexus URL
    user: admin  # Username for Nexus
    password: admin123  # Password for Nexus
    method: POST  # HTTP method for creation
    ldap_name: "my-ldap-server"  # Name for the LDAP server (required)
    ldap_protocol: "LDAP"  # Protocol (required)
    ldap_useTrustStore: false  # Don't use a trust store (optional)
    ldap_host: "ldap.example.com"  # LDAP server hostname (required)
    ldap_port: 389  # LDAP server port (optional, default 389 for LDAP)
    ldap_searchBase: "dc=example,dc=com"  # Search base for LDAP queries (required)
    ldap_authScheme: "SIMPLE"  # Authentication scheme (required)
    ldap_authUsername: "admin"  # Username for LDAP binding (required)
    ldap_authPassword: "secretpassword"  # Password for LDAP binding (required)
    ldap_connectionTimeoutSeconds: 30  # Timeout for LDAP connection (optional)
    ldap_connectionRetryDelaySeconds: 300  # Delay between connection retries (optional)
    ldap_maxIncidentsCount: 3  # Maximum failed connection attempts (optional)
    ldap_userSubtree: true  # Search user subtree (optional)
    ldap_userObjectClass: "user"  # User object class in LDAP (required)
    ldap_userIdAttribute: "sAMAccountName"  # Attribute for user ID (required)
    ldap_userRealNameAttribute: "cn"  # Attribute for user real name (required)
    ldap_userEmailAddressAttribute: "mail"  # Attribute for user email address (required)

- name: Set LDAP server order
  collection.sonatype_nexus.nexus_security_ldap_order:
    url: "http://172.18.0.3:8081"
    user: admin
    password: admin123
    order_list:
      - "secondary"
      - "my-ldap-server"
      - "my-ldap-server2"

